osx_image: xcode8

sudo: required
dist: trusty
group: edge

services:
  - docker

language: node_js

os:
  - linux
  - osx

node_js:
  - '4'
  - '5'
  - '6'

env:
  global:
    - secure: "KPf6trtYLBDc2S/fF7H4VkNOAQ2Gc9sFj3v8aHOhNWDagACEHaPjIZdr3MGmzXji2EyQqtm6SxBxzdMbe1BNY5GRALgGI2fSyra+VwjhUeOB/UJ8oZuxhqnywbF77lbZgUYK/kOWHgCKGQxRsVZyytgK2CihOwPwzSp/CWUhBjlyjtDpUOMJXfc0USg05imR9LcwdW9o84uXGyI3XwHhqsA5szlu09Oxz+O//TMCHobb8o9b13N8Oxhdu9mgzynXCEo7TG4rwbmx2t7ymfM0TfEqfEsOOQ/A7iPJ4lxQ+FKGoKaqfITuZtUmzd4RaCK8zRVg/dYbXX2qF/RWRBKwIAfBLNLYYdFxleaBaNgGGyQw8TpNkm80u5ilmIDCrw79m0MqePZXcL4pdfRC9PBE2PO55tX/Podhk9HKovixvB4qxUj3Y45ORtSE2TO78W3Cs54JTQVNh4xz8Tzp67DWwNXN5XnwkVyvRugaCHV1gUuJWuJTUr6Bdoad9vid+GUKqNoBlTTgkjfc0/TDSuDFnAbnhdga4xFoFLnpTDpCaZrr1NWfhVCepGqY7I4qLcie/Bobpr6n8UuBRg6devdcBZJxAYKyC4SkfqfkJe36TmTViz7GCs698CAPteJ2ypifeERT9zYu0JYeofEi49bPxevaaFICxzUE2WIAlGeGIw0=" # DOCKER_EMAIL
    - secure: "Xh5xnUckiGwr3pcl44c8A91p2AyhJXMpGzDPpTk+63ZeM0nDnUh1/1StqW+5Bfx24MI6HtkOiGa7zTn8HbDMWXVN7s+eZ0eC28GI63EsKyivsMyylR+mwMKsAHcxbfZvFaDJiYE/s1FXXVdIr3PpNVxlncbuZiTQ+i+sr4iD+B14UV+GTwgbpyNEF2jSK+MlV0XAn6AK4kc6fd3Zx2guG9Kv8slwFcK7Kwjpa4C+t0ZX85wiqlPBhC42nhx6eRUwWbf/4rySd/4RhHXan+zsBWBjUHLhjzMvwsahqPg0yBzkFoZ3ozUQqv9NhmyjEANCAAj1vcOoFZ0nikgfR1WqeMEcKfTFbV0QVfqnEyYHN2ZUmvOzv2gih26gHaY7E2Dte6u96CSv5TgwYtiCBZzc0vHO8p2+heLfourhqdQhanElq4nthBffKJled5dOcq6UAINK85ZwzS+7EZG79idGETR7vvCiaLLuhCn4kFdo1fLOCTQ+FJAOYw3uSk6n1YlNbxNJ7RwykgRB/9MgbJHc9o67C/Y3NEzBRErSctqfZ9Rg6gICM8dkwoBh0652FDn4E/TCkpfKbpTkRkJoFzRxe9joFTYvkt+fIYwokyajgt/qlpb6XQiFiUqdlWcWcYDNbBSnIMfH4L61ktMtCCcv85Iw98d1bxi93r/UdyhWOuQ=" # DOCKER_USER
    - secure: "vthH2fNi44W4+21OxLnmeb41y9T+v5p4vpWgj5DG/LuVfJNw5fNvnitXdwe3UR0EQCvH0ow4mn4I2avqvn5G6PSDmgpzTHcw8OJt/cGhXXsN629tdccG+rHG8xFneRACnSJOmZ3rU038igAlZt7PdraM68ZVdwZfXEDua06qb4FODBWNZtiUJ89AyYib5DoYjde18sEHqNZEp1ruhcfZArzexnxJ7G63Qe3SmxBS5Z7jC18sGyTI3FbUyKUlqYsxG8rcqTy5QOKa6Y0P1TPPHmr517uO4YfxhQX6Lcrn+DgvHH/n6pzlBeGgXm5XZB+MN6iRM8NRo1VmQ8Ecm3sFb6UZvESB0wx3EI5DPde/rxE6fwhTP/d+95qSrZUvuqLOGfa6Zb5JsgKzK4St2EVb6hs5qqTnIifGZQZ4NJrhTe737kE4FsJbK8dQmNMwMlNVbCmnYeZmWh3aJgXp4fjk/RyomFvfGLjNchVIM6iZw2DlqLJm2Wl4Dsb1blj4tfuL0+UlA9YiF2V6ycn5sWdq5JiGsWhkyARnCiSFc5lu6TbvKt8k5CQIwZXshoKyv8IIQkEubGVQRI9D8nDrgrbOt8+lIEU6Ibfbi1CzuPpv95GodWLCEyf6KXf8EHr+tEbKPwpbNzIsPWEqMuPQ6F3AWtGnuuAvfLm/5+/OXNKxT3o=" # DOCKER_PASS
    - secure: "4Oa9zPbUjYNC/MzXCJW/FF0nATazifi3r+VDyonEa9RM3PiJO31BMJCmJP24PgCyjie4wqiGGJcskIhAKBpY3YZui4SNUBYS50Z6E7c1D8mPMdd+bYt7t7sNAUPmWL+zJruNya7Hg2vt5lt/wbrRb+SVAxwxM2gtmVDngio+PTPcBklGMbZkB758vvk5QtFo/cIUbZnGRiBJUoGSinMVz5kJlBgE7afTnX0oSTCx0SbhPO2pfG8iYbtWO/ar3AoPuKCIKSsBoCu6eXXIwlSJg/+q3nTXGJRfMm7j0jOSrG1O5CqemJbH7I0VDfDLE9h8xj3fPUpUtxwWPqaOiZPEHVXjOmbkZhinW6rjDplBh7T2A6bdUbdtK+8K/W7fLZV2kA2qDClI77r18nvYvPXzn6VBGFb27RxE3/5LopekwgzyEpssS4G1VXrB09ptmlJl2bGytou4DXOipLMLoRkUkiE+V9KdGg6kpYAdUPgjYN3COActU9/Gt3ltqWGnL0gXOzuyR2Y807nubaVKNVoWI3YO8FZ1QMOVE83NnQarnB6EC47BVSxRizbKMrvCeA8UZgeHBBdblOXiq9RtcG3h90E22zVin0UBNvtC5RyiUQWjZ2vpMVAXL9JqOnoQxOJjY/nVzbux02GG028WQpg9u7y1oJrxcQ4P4gN1IyyMI7Y=" # GITHUB_TOKEN
    - secure: "zn6ZQM7LFgFcwFNqcbhBGY9DYZzw3tOa3puTntdcEfnMsp+ikcJSYl8lvTj1TL1rvZIAJfO896Uk79HTyJtv06a9LjpEElaQvkBEtPGnE0fdGWLgK1cl0JBxPNEDicAoYrUV2QkuuwaTtpKeUsnD6XmWSzzpqmZKDLfRyO1xwHyvH4aTvqAhDXM7Hb+Hae4Nk7ZCq5v1CwScu6gdaJMBPdcmWBzAPNnAJYbDilw3fFdfOrxhuTagmmBQFn99iaIRbLR4sTuI/c53NMUS8FJyfistTVVuMOFTSdFvlQ/Ikm6PbIYYIMDp9RetGIJk7IL4U18LpwACzhjc25SvWrQXPI7eiW0H3uD8rGPtR50cBrbxRI/Of7271eqXvtNMzHSsCo0ENQ1qYWoF5OhI4roklAfZjQpdi7Ngg+EPNIgf24vpf0fI9u8caOHxzAYjrwdcXCLTmcu0ANuQMMXP5G7mBZG5/kGzC5cpc11uqwINCU10rVQa7JVNuFNhuT98/c+DSeBY92w9nEsCshG1AKcNjY677FbBdVS+DCPPRjiAfjomT9Ma8VqR/bGCogzaEaA7adUbGLGI9V397QF9gSrzyBP/zjOiYVX1mRjylmEitdQtXF3CXsbhrOOCenDifKHhtnOgXgpObcbwV4B82VhGzDOvTxF2n+QTGhUAA/Okyv8=" # CSC_LINK
    - secure: "LenBHoTcLW6cF7ML3+dB7JICMzEkawrJHiqFcGSo+hgapB0NCHGUiihr2zrjGSlHmElPiQ2TCnCRmPvOzVfpZswg36D0+1niPgZ+0vfGfPEoPmHhlvIsMPLb7v0lCIeh8z2o9eNbSvnv6NRXS4o5NLlHzM+RhAYARSXvRmFxqCCBn1Sj9pB5TB9NX3mK0Lb3mEJcIgEVFBr/xLiISPUBGFmncHUpxYjZHwxXQXRcGyfOEphLM9tvmEdoILRxM67k035csAIeaLKKPJcMGmO0e/JwZacQN7s3MhD2M8NddhQvWklNjabXAJ0L9Ycujf6rI5RsGcZL2U80HKr0aYRMiVW7/MPMpLARFOUoLfuFAXKkkLHp7Lbb1W6Zftr4yxkrfDXIQsh976HkBj+czr6wGwzBwb39zX4KEm/Yc3TEIxC/kKs9bt+vVW6BG+J41neiDiuIY1D1tRA0OEq0j04zpU6n683ojfYddzFoUWCN+TB3i0HQxWsKTOGKdcQwrJs7xZ4//UzD/vOTHj18SH0nm6ImF2/7q+9wJO646gHWTGTjGFYdupuR402wb3h5vWmGfFRvX6B1QtYImmEwMFnqf2XRwTTSz3niKn2Rt1YUiCP5bEz+Dcr+e+A8Jidt6ZuJEXv5SbykTG4YBmgCuuFT5KRwv08kule7FiUtQ2KD5XE=" # CSC_KEY_PASSWORD

cache:
  directories:
    - $HOME/.electron

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - gcc-multilib
      - g++-multilib

before_install:
  - git --version
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  #
  # https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#os-x
  #
  # Use brew to install required packages.
  #
  # To build app in distributable format for Windows on OS X:
  # $ brew install Caskroom/cask/xquartz wine mono
  #
  # To build app in distributable format for Linux on OS X:
  # $ brew install ruby gnu-tar libicns graphicsmagick
  #
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
    fi
  - npm install -g npm
  - npm --version

install: travis_wait 40 npm install

script:
  - |
    if [[ -z "$TRAVIS_TAG" ]]; then
      npm run build-latest
    else
      npm run build
    fi

after_success:
  - mkdir -p releases
  - PACKAGE_NAME=`scripts/package-name.sh src/package.json`
  - PACKAGE_VERSION=`scripts/package-version.sh src/package.json`
  - RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
  - COMMIT_LOG=`git log -1 --format='%ci %H %s'`
  - |
    # build:mac-x64
    if [[ "$TRAVIS_NODE_VERSION" == "4" && "$TRAVIS_OS_NAME" == "osx" ]]; then
      # https://github.com/electron-userland/electron-builder/issues/398
      security import "scripts/certs/Certum-Code-Signing-CA-SHA2.cer" -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign;
      # https://github.com/electron-userland/electron-osx-sign/issues/83
      # Temporarily Bypass Gatekeeper
      sudo spctl --master-disable;
      sudo spctl --status;
      npm run build:mac-x64;
      ls -al output output/*;
      cp -af "output/mac/${RELEASE}.dmg" "releases/${RELEASE}-mac-x64.dmg";
      ls -al releases/*;
      if [[ -z "$TRAVIS_TAG" ]]; then
        npm run github-release -- \
          --owner=cheton \
          --repo=cnc \
          --tag="${TRAVIS_BRANCH}-latest" \
          --name="${TRAVIS_BRANCH}" \
          --body="${COMMIT_LOG}" \
          "releases/${RELEASE}-mac-x64.dmg";
      fi
    fi
  - |
    # build:linux-ia32
    if [[ "$TRAVIS_NODE_VERSION" == "4" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      npm run build:linux-ia32;
      ls -al output output/*;
      cp -af "output/${PACKAGE_NAME}_${PACKAGE_VERSION}_ia32.deb" "releases/${RELEASE}-linux-ia32.deb";
      pushd releases;
      ln -sf ../output/linux-ia32-unpacked "${RELEASE}-linux-ia32";
      tar zcfh "${RELEASE}-linux-ia32.tar.gz" "${RELEASE}-linux-ia32";
      rm -f "${RELEASE}-linux-ia32";
      popd;
      ls -al releases/*;
      if [[ -z "$TRAVIS_TAG" ]]; then
        npm run github-release -- \
          --owner=cheton \
          --repo=cnc \
          --tag="${TRAVIS_BRANCH}-latest" \
          --name="${TRAVIS_BRANCH}" \
          --body="${COMMIT_LOG}" \
          "releases/${RELEASE}-linux-ia32.deb" "releases/${RELEASE}-linux-ia32.tar.gz";
      fi
    fi
  - |
    # build:linux-x64
    if [[ "$TRAVIS_NODE_VERSION" == "4" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      npm run build:linux-x64;
      ls -al output output/*;
      cp -af "output/${PACKAGE_NAME}_${PACKAGE_VERSION}_amd64.deb" "releases/${RELEASE}-linux-x64.deb";
      pushd releases;
      ln -sf ../output/linux-unpacked "${RELEASE}-linux-x64";
      tar zcfh "${RELEASE}-linux-x64.tar.gz" "${RELEASE}-linux-x64";
      rm -f "${RELEASE}-linux-x64";
      popd;
      ls -al releases/*;
      if [[ -z "$TRAVIS_TAG" ]]; then
        npm run github-release -- \
          --owner=cheton \
          --repo=cnc \
          --tag="${TRAVIS_BRANCH}-latest" \
          --name="${TRAVIS_BRANCH}" \
          --body="${COMMIT_LOG}" \
          "releases/${RELEASE}-linux-x64.deb" "releases/${RELEASE}-linux-x64.tar.gz";
      fi
    fi
  - |
    # tinyweb
    if [[ "$TRAVIS_NODE_VERSION" == "4" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      pushd examples;
      zip -r "../releases/${RELEASE}-tinyweb.zip" "tinyweb";
      popd;
      ls -al releases/*;
      if [[ -z "$TRAVIS_TAG" ]]; then
        npm run github-release -- \
          --owner=cheton \
          --repo=cnc \
          --tag="${TRAVIS_BRANCH}-latest" \
          --name="${TRAVIS_BRANCH}" \
          --body="${COMMIT_LOG}" \
          "releases/${RELEASE}-tinyweb.zip"
      fi
    fi
  - |
    # docker image
    if [[ "$TRAVIS_NODE_VERSION" == "5" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      travis_wait scripts/travis-docker-build.sh;
    fi

before_deploy:
  - echo "Deploying to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: "oFmp9ufvaj47S+TEwZreEuCLHcPkgxu4lc5G8IKeVoasMY6pkUTKmmfloH9X5Kt3bJEmH3Bmc7/qsjaBSY5r4yuK8L2BagSKxbPiPP6Hr7i8siFqZvg2Z99ciO3gy7FC1LEWsVqySoO2IhemI0J/v6w4oBYiD1RnsncTtr9a5aPW0ffjqdzV0/Qnzr9wMSy6S80z/6vLUZm4KVFXBbEo1185vqU/fFggWJJFA46Hb8+shQO7qcFQuHVtd1qAUrnaoibYaYPqOVdjIwn04jG+BEbT8Dy8IDlNy77LzgqmQtDpf/Ajkegha6WRusVB5icJM7aUl4xLZICCNuG8DLm9LZRdc7zHvnKY55M3qGLGtv6tdkHgQsdj6oCzsn7pPZRhKyRYUZjbzxJJIQ0dVLmv1bLK/5IbOWk5TCt3fHw0kJtWNWPh1GjForW9JUioTVZZbac22tVZnRP32o/pnnACIjpqPLOC3Ubc/2BmmZ/WgV4K4SHJFNTCpn797vMT6YygWdhOrfueBHp2XuJWwpCmc3GGfgZiq3F0g4IpBBnY6Kuddmy1mGJdCLU6X5vlrDZfJQGQvdhP9avMI3prZHwCcqlavgLTr5Ntgg50QdMIFKTddGRrVPb11UjurYPLohZThS4WrHUx99F85GVJxqew/QyJgKJKiW1h8e//JTE0B7o="
  file_glob: true
  file:
    - 'releases/*.*'
  overwrite: true
  skip_cleanup: true
  on:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on
    tags: true  # Deploy app only when a tag is applied to the commit
    node: '4'
