title: CNCjs
description: keep calm and make something of amazing
logo: docs/assets/images/logo.png
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-coffeescript
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
noscript: false
kramdown:
math_engine: mathjax
syntax_highlighter: rouge
